[package]

name = "crap_rsa"
version = "0.0.1"
authors = ["Corey Richardson <corey@octayn.net>"]
license = "BSL-1.0"

[dependencies.rust-gmp]

git = "https://github.com/cmr/rust-gmp"
branch = "crypto"

[dependencies]
docopt = "*"

[[bin]]
name = "rsa_enc"
path = "src/rsa_enc.rs"
